project:
  type: website
  output-dir: _site
  resources:
    - data/
  render:
    - "*.qmd"
    - "session1/*.qmd"

website:
  title: "36104 · Data Visualisation and Narratives"
  navbar:
    background: "#4e4a84"
    left:
      - text: "Session 1"
        menu:
          - href: session1/part-a.qmd
            text: "Part A · Allometry"
          - href: session1/part-b.qmd
            text: "Part B · The Tree of Life"
          - href: session1/part-c.qmd
            text: "Part C · The Triangle of Everything"
          - href: session1/part-d.qmd
            text: "Part D · The Periodic Spiral"

format:
  live-html:
    theme: [cosmo, theme.scss]
    toc: true
    toc-depth: 2
    code-tools: false
    grid:
      body-width: 900px
